spring.application.name=CreditCardAuthorization
#[local]
#spring.datasource.url=jdbc:postgresql://localhost:5432/JavaSchoolProject
#spring.datasource.username=postgres
#spring.datasource.password=123456
#[Fly.io]
spring.datasource.url=${JDBC_URL:jdbc:postgresql://creditcard-db.internal:5432/creditcard-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
vaadin.urlMapping=/app/*